quarkus:
  datasource:
    db-kind: postgresql
    reactive:
      url: postgresql://localhost:5432/users
    username: quarkus
    password: quarkus
  hibernate-orm:
    database:
      generation: drop-and-create