quarkus:
  datasource:
    db-kind: postgresql
    reactive:
      url: postgresql://localhost:5432/users
    username: user
    password: password
  hibernate-orm:
    database:
      generation: drop-and-create